### PR TITLE
Fix payment display

### LINKED ISSUE #154: When we first got onto the QC survey page it didn't seem to show the correct payment amount
Instead it was showing what had been computed last time the callback had been run

### PR DESCRIPTION
**Pull request by kepstein23**
closes #154

### CODE REVIEW

File: client/src/intro-exit/Surveys/quality_control.jsx [hunk 1]
```diff
@@ -1,26 +1,39 @@
...
     }, [])
+
+    
     const dollarsOwed = player.get("dollarsOwed");
+    useEffect(() => {
+        setDisplayPayment(dollarsOwed)
+    }, [dollarsOwed])
 
+    useEffect(() => {
+        player.set("stopPaying", true)
```
Comment (JamesPHoughton) [inline client/src/intro-exit/Surveys/quality_control.jsx:27]: Werent we going to set `stopPaying` in the previous useEffect, with the setDisplayPayment? That way it didn't run before the payment calculation callback had finished? The way it is here, wouldn't it get called as soon as the component loads the first time, and possibly happen before the payment calculation callback happened?

File: client/src/intro-exit/Surveys/quality_control.jsx [hunk 2]
```diff
@@ -1,26 +1,39 @@
...
     useEffect(() => {
+        console.log("isPaidTime before" + player.get("isPaidTime"))
         player.set("isPaidTime", false); //stop paying participant when they get to this screen (so we can compute the time)
+        console.log("isPaidTime after" + player.get("isPaidTime"))
         console.log("QC Exit. Played for " + player.get("activeMinutes") + " minutes, earned $" + player.get("dollarsOwed"))
     }, [])
+
+    
     const dollarsOwed = player.get("dollarsOwed");
+    useEffect(() => {
```
Comment (JamesPHoughton) [inline client/src/intro-exit/Surveys/quality_control.jsx:22]: We should double check that this doesn't get called at render, but only when the dollarsOwed changes. Now that I think about it, when dollarsOwed is set from player.get, that might be enough to trigger this...
This might be the pattern we want: https://medium.com/swlh/prevent-useeffects-callback-firing-during-initial-render-the-armchair-critic-f71bc0e03536

File: server/src/callbacks.mjs [hunk 3]
```diff
@@ -99,6 +99,7 @@ Empirica.onNewPlayer(function ({player}) {
 Empirica.onPlayerConnected(function ({player}) {
   console.log("Player " + player.participant.identifier + " connected." )
   player.set("isPaidTime", true)
+  player.set("stopPaying", false);
```
Comment (JamesPHoughton) [inline server/src/callbacks.mjs:102]: lets go into this together tomorrow morning. =)

**Review by JamesPHoughton — APPROVED** [review]
